# see https://github.com/ankane/blazer for more info
# TODO: Review https://blazer.dokkuapp.com/dashboards/1-dashboard-demo
# TODO: Review https://github.com/ankane/blazer?tab=readme-ov-file#charts


data_sources:
  primary:
    url: <%= Rails.env.production? ? "sqlite:storage/production_primary.sqlite3?mode=ro" : "sqlite:storage/development_primary.sqlite3?mode=ro" %>
  cache:
    url: <%= Rails.env.production? ? "sqlite:storage/production_cache.sqlite3?mode=ro" : "sqlite:storage/development_cache.sqlite3?mode=ro" %>
  queue:
    url: <%= Rails.env.production? ? "sqlite:storage/production_queue.sqlite3?mode=ro" : "sqlite:storage/development_queue.sqlite3?mode=ro" %>
  cable:
    url: <%= Rails.env.production? ? "sqlite:storage/production_cable.sqlite3?mode=ro" : "sqlite:storage/development_cable.sqlite3?mode=ro" %>
  # url: <%= ENV["BLAZER_DATABASE_URL"] %>

    # statement timeout, in seconds
    # none by default
    # timeout: 15

    # caching settings
    # can greatly improve speed
    # off by default
    # cache:
    #   mode: slow # or all
    #   expires_in: 60 # min
    #   slow_threshold: 15 # sec, only used in slow mode

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      # user_id: "/admin/users/{value}"

    smart_columns:
      # user_id: "SELECT id, name FROM users WHERE id IN {value}"

# create audits
audit: true

# change the time zone
# time_zone: "Pacific Time (US & Canada)"

# class name of the user model
user_class: AdminUser

# method name for the current user
user_method: current_admin_user

# method name for the display name
user_name: email

# custom before_action to use for auth
# before_action_method: authenticate_admin_user! && current_admin_user.has_role?(:super_admin)

# email to send checks from
# from_email: blazer@example.org

# webhook for Slack
# slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

# enable anomaly detection
# note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: prophet / trend / anomaly_detection

# enable forecasting
# note: with trend, time series are sent to https://trendapi.org
# forecasting: prophet / trend

# enable map
# mapbox_access_token: <%= ENV["MAPBOX_ACCESS_TOKEN"] %>

# enable uploads
# uploads:
#   url: <%= ENV["BLAZER_UPLOADS_URL"] %>
#   schema: uploads
#   data_source: main
