default: &default
  databases: [cache]
  store_options: &default_store_options
    max_age: <%= 60.days.to_i %>
  size_estimate_samples: 1000

development: &development
  <<: *default
  store_options:
    <<: *default_store_options
    max_size: <%= 256.gigabytes %>

production: &production
  <<: *default
  store_options:
    <<: *default_store_options
    max_entries: <%= 256.gigabytes %>