name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: bundle install

      - name: Lint code for consistent style
        run: bin/rubocop

      # - name: Scan for known security vulnerabilities in gems used
      #   run: bin/bundler-audit

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --quiet --no-pager

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

      # - name: Deploy app
      #   uses: superfly/flyctl-actions/setup-flyctl@master
      #   run: flyctl deploy --remote-only
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
