name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: bundle install

      - name: Lint code for consistent style
        run: bin/rubocop

      - name: Scan for known security vulnerabilities in gems used
        run: bin/bundler-audit --ignore GHSA-353f-x4gh-cqq8 GHSA-mqcp-p2hv-vw6x

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --quiet --no-pager

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test
